config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :friends, only: [:index, :show]
  resources :users, except: [:index]
  resources :user_sessions, only: [:create]
  resources :musics, only: [:index, :show]

  get '/register' => 'users#new'
  get '/login'    => 'user_sessions#new'
  get '/logout'   => 'user_sessions#destroy'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_many :friend_users
  has_many :users, through: :friend_users
end

app/models/friend_user.rb
class FriendUser < ActiveRecord::Base
  belongs_to :friend
  belongs_to :user
end

app/models/music.rb
class Music < ActiveRecord::Base
  has_many :music_users
  has_many :users, through: :music_users
  has_many :scores

  scope :level_by, -> (*levels) { where(level: [levels].flatten) }
end

app/models/music_score_crawling.rb
class MusicScoreCrawling < ActiveRecord::Base
  belongs_to :user

  enum status: %w(pending start_failed start_successed)

  def start
    self.started_at = Time.current

    @valanga = Valanga::Client.new

    start_successed!
  rescue
    start_failed!
    raise $!
  end
end

app/models/music_user.rb
class MusicUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :music
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :music
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.require_password_confirmation = false
  end

  has_many :music_users
  has_many :musics, through: :music_users

  has_many :friend_users
  has_many :friends, through: :friend_users

  has_many :music_score_crawlings
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  helper_method :current_user, :logged_in?

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless current_user
      store_location
      redirect_to login_url, alert: "You must be logged out to access this page"
    end
  end

  def store_location
    session[:return_to] = request.url
  end

  def redirect_back_or(default, options)
    url = session[:return_to] || default
    redirect_to(url, options)
    session.delete(:return_to)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def friend_params
    params[:friend]
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show]

  # GET /musics
  # GET /musics.json
  def index
    if search_query_exist?
      # FIXME: Not only To be searchable by name but also such as artist name, etc..
      @musics = current_user.musics.where("name LIKE ?", "%#{search_query[:q]}%")
    elsif difficulty_query_exist?
      @musics = (@musics || current_user.musics).level_by(params[:level])
    else
      @musics = current_user.musics
    end

    @musics = @musics.page(params[:page]).per(15)
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
    # FIXME: render 404 page
    unless @music
      render status: 404
    end
  end

  private

  def set_music
    @music = current_user.musics.find_by(id: params[:id])
  end

  def search_query
    params.permit(:q, level: [])
  end

  def search_query_exist?
    search_query.key?(:q)
  end

  def difficulty_query_exist?
    search_query.key?(:level)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  # GET /login
  def new
    @user_session = UserSession.new
  end

  # POST /user_sessions
  def create
    @user_session = UserSession.new(user_sessions_params)

    if @user_session.save
      redirect_back_or(musics_path, notice: "Login successful")
    else
      redirect_to login_url, alert: 'Login failed.'
    end
  end

  # DELETE /logout
  def destroy
    current_user_session.destroy
    redirect_to root_url, notice: 'Logout successful.'
  end

  private

  def user_sessions_params
    params.require(:user_sessions).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    @user.save!
    redirect_to @user, notice: t('.success')
  rescue ActiveRecord::RecordNotUnique
    @user.errors.add(:name, t('.not_unique'))
    render :new
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.update!(user_params)

    redirect_to @user, notice: t('.success')
  rescue ActiveRecord::RecordNotUnique
    @user.errors.add(:name, t('.not_unique'))
    render :edit
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to users_url, notice: t('.success')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_form.html.slim
= form_for @friend do |f|
  - if @friend.errors.any?
    #error_explanation
      h2 = "#{pluralize(@friend.errors.count, "error")} prohibited this friend from being saved:"
      ul
        - @friend.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/friends/index.html.slim
h1 Listing friends

table
  thead
    tr
      th
      th
      th

  tbody
    - @friends.each do |friend|
      tr
        td = link_to 'Show', friend

app/views/friends/show.html.slim
p#notice = notice

'|
= link_to 'Back', friends_path

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'shared/meta'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top[role="navigation"]
      .container
        = render 'shared/header'
    .container
      = render 'shared/flash'
      = yield

app/views/musics/index.html.slim
h1 Listing musics

.input-group
  = form_tag musics_path, method: :get do
    = text_field_tag :q, nil, { class: "form-control" }

    .btn-group.btn-group-lg[data-toggle="buttons"]
      - Settings.music.levels.each do |l|
        .btn.btn-default
          = check_box_tag 'level[]', nil, false, id: "level_#{l}", value: l
          = l

    .btn-group[data-toggle="buttons"]
      - Settings.music.difficulty.zip([:success, :warning, :danger, :primary]) do |d, klass|
        .[class="btn btn-#{klass}"]
          = check_box_tag 'difficulty[]', nil, false, id: "difficulty_#{d}", value: d
          = d

    br

    = button_tag name: :search, class: "btn btn-default" do
      span[class="glyphicon glyphicon-search" aria-hidden="true"]
        = t('.search')

br

.panel.panel-default
  table.table.table-bordered.table-hover
    thead
      th = t('.name')
      th = t('.difficulty')
      th = t('.level')
      th = t('.achivement_rate')
      th = t('.score')
    tbody
      - @musics.each do |music|
        tr[data-href=music_path(music)]
          td = music.name
          td = music.difficulty
          td = music.level
          td = music.achivement_rate
          td = music.score

= paginate @musics

app/views/musics/show.html.slim
p#notice = notice

p
  strong Name:
  = @music.name
p
  strong Score:
  = @music.score

= link_to 'Back', musics_path

app/views/shared/_flash.html.slim
- flash.each do |name, msg|
  = content_tag :div, :class => "alert alert-#{ name == "alert" ? "danger" : "success" } alert-dismissable", :role => "alert" do
    button.close[type="button" data-dismiss="alert"]
      span[aria-hidden="true"]
        | ×
      span.sr-only
        | Close
    = msg

app/views/shared/_flush.html.slim
- flash.each do |name, msg|
  = content_tag :div, :class => "alert alert-#{ name == "alert" ? "danger" : "success" } alert-dismissable", :role => "alert" do
    button.close[type="button" data-dismiss="alert"]
      span[aria-hidden="true"]
        | ×
      span.sr-only
        | Close
    = msg

app/views/shared/_header.html.slim
.navbar-header
  button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"]
    span.sr-only
      | Toggle navigation
    span.icon-bar
    span.icon-bar
    span.icon-bar
  = link_to "Reflec Board", root_url, :class => "navbar-brand"
#navbar.collapse.navbar-collapse
  ul.nav.navbar-nav.navbar-right
    - if logged_in?
      li
        = link_to t('.account_setting'), edit_user_path(current_user)
      li
        = link_to t('.logout'), logout_url
    - else
      li
        = link_to t('.signup'), register_url
      li
        = link_to t('.login'), login_url

app/views/shared/_meta.html.slim
/ See https://github.com/kpumuk/meta-tags#allowed-options-for-display_meta_tags-and-set_meta_tags-methods

- set_meta_tags site: t('site_title'), reverse: true
- set_meta_tags description: t('meta.description')
- set_meta_tags keyword: t('meta.keywords')
- set_meta_tags og: t('meta.og')
- set_meta_tags twitter: t('meta.twitter')

meta charset="UTF-8"
meta http-equiv="X-UA-Compatible" content="IE=edge"
meta name="viewport" content="width=device-width, initial-scale=1"
meta name="author" content=""

= display_meta_tags

app/views/top/index.html.slim
h2
  = t('.subject_html')

app/views/user_sessions/_form.html.slim
= simple_form_for(:user_sessions, url: :user_sessions) do |f|
  / FIXME: It is supposed to be unnecessary `label: t('xxx')`.
  = f.input :username, label: t('authlogic.attributes.user_session.username')
  = f.input :password, label: t('authlogic.attributes.user_session.password')
  .actions
    = f.button :submit, 'login', class: 'btn btn-lg btn-primary'

app/views/user_sessions/new.html.slim
.row
  .col-xs-8.col-xs-push-2
    = render 'form'

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.input :username
  = f.input :email
  = f.input :password
  .actions
    = f.button :submit

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form'
= link_to 'Back', root_path

app/views/users/new.html.slim
= render 'form'

app/views/users/show.html.slim
p#notice
  = notice
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', root_path